#!/usr/bin/za

doc `
    fix test:
        FIX should only be used for serious fault recovery.
        it is mainly intended for returning a known error or 
        for cleaning up resource use.
`

define chained(p)
    return p
end

define in_fn_test(p)
    q = p.chained?
    w = nil?
    return q
  fix
    println "(fn) info : ",_try_info
    println "(fn) line : ",_try_line
    return -1
end

#------------------------------------------------------------------------------------

z=fopen("/tmp/dhop-missing","r") ? "file1" 
# resume in "fix file1" starts again from here
on not z is nil do z.fclose

println in_fn_test(42)
println in_fn_test(nil)

if nil?
    println "should not see this as there is no resume in unlabelled FIX below."
endif


#------------------------------------------------------------------------------------
fix file1
    println "(main-file-err) info : ",_try_info
    println "(main-file-err) line : ",_try_line
    resume
fix
    println "(main)"
    println "(main) info : ",_try_info
    println "(main) line : ",_try_line
#------------------------------------------------------------------------------------
fix
    println "(main) this one shouldn't be reached."

